### ISSUE TITLE
Works great in Firefox but not others.

### ISSUE THREAD

**Issue by jhample** [battatech/battatech_excelexport#35]
This works perfectly in FF but not in Chrome, Safari, or IE.  Any fix for that?

**Comment by tarunbatta** [comment]
Supported browser details are,
Chrome, supported in all versions
Firefox, supported in all versions
Opera, supported since 7.2
Safari, supported in all versions
Internet Explorer, not compatible.

So, it should be working on Chrome. Please share the your code, and the dataSet you are exporting

**Comment by jhample** [comment]
Thank you for the prompt reply!  I'm using the Export on this page: http://www.rhjacobson.com/admin/_plugins/admin-section-pages/prospects-report-pages/
When I export from Firefox, it automatically opens Excel and launches the spreadsheet... great!  In Chrome and Safari, it triggers a download of an "Unknown" file type.  I'm using a Mac.  Thanks!

**Comment by tarunbatta** [comment]
The problem is that you are trying to export a lot of data. The plugin uses dataUri feature of the browser, and different browsers have different limit size of dataUri. Therefore, you are facing issue in other browsers. If you try to small dataset, it will work.

Moreover, for your case (large dataset), I would recommend using this plugin, 
https://github.com/battatech/battatech_ServerSideExcelExport

Let me know if that helps.

**Comment by jhample** [comment]
Will give this suggestion and the other link a try.  Thanks again!
